### ISSUE TITLE
Current temperature cannot be shown dynamically

### ISSUE THREAD

**Issue by ZIV-LY** [willasm/obsidian-open-weather#25] opened 2024-04-08 10:22 UTC
Thank you for your plugin. Your plugin and template are very useful.
However, the current temperature cannot be shown dynamically when the mouse is hovering. I find that if I transform to source view and then transform back to preview, the function will be normal. Maybe it is a small bug.

**Comment by willasm** [comment] 2024-04-18 04:12
Sorry for not getting back to you sooner, been very busy. This has been a long standing issue that has been bugging me for a long time. Closing and re-opening the note also fixes it even just switching to another note and back can also fix it. The odd thing is it works correctly for me most of the time making it very difficult to track down the cause. In fact, I have been trying to trigger it again for the last half hour without success. I will dig deeper into this once again to see if I can track down the cause...

**Comment by ZIV-LY** [comment] 2024-04-18 10:03
> Sorry for not getting back to you sooner, been very busy. This has been a long standing issue that has been bugging me for a long time. Closing and re-opening the note also fixes it even just switching to another note and back can also fix it. The odd thing is it works correctly for me most of the time making it very difficult to track down the cause. In fact, I have been trying to trigger it again for the last half hour without success. I will dig deeper into this once again to see if I can track down the cause...

Hi Willasm, thank you so much for your reply. This small bug doesn't affect too much. Appreciate your effort on the plugin.

**Comment by willasm** [comment] 2024-09-10 03:07
I just want to inform everyone that this plugin in being discontinued. Open Weather has discontinued the API 2.5 on which this plugin is based. I have however created a new plugin using the Visual Crossing Weather API and it follows the same basic approach to representing the weather as this plugin did so it should be relatively easy to move over to the new plugin. While it is still in development it is almost 100% functional. The documentation however is almost non existent but the list of available macros is complete and is in a nicely formatted table for better viewing. I hope to have it published soon as it is very close to being completed. If you want to try it before it is released you can find it on Github [here](https://github.com/willasm/vc-weather).

Thank you, William McKeever

**Closed as completed by willasm** 2024-09-10 03:07 UTC
